nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['http://localhost:3000'] # Add your React app's origin
        allow_headers: ['Content-Type', 'Authorization', 'Accept', 'X-Requested-With']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: ['Link']
        max_age: 3600
